# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-Ping
version:      1.04
version_from: Ping.pm
installdirs:  site
requires:
    POE:                           0.11
    Time::HiRes:                   1.2

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
