--- #YAML:1.0
name:                POE-Component-Client-Ping
version:             1.14
abstract:            POE component for non-blocking/concurrent ICMP ping.
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    POE:                           0.11
    Time::HiRes:                   1.2
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Rocco Caputo <rcaputo@cpan.org>
